server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location /agent-demo/ {
        try_files $uri $uri/ /agent-demo/index.html;
    }
    location /genre-classifier/ {
        try_files $uri $uri/ /genre-classifier/index.html;
    }
    location /image-classifier/ {
        try_files $uri $uri/ /image-classifier/index.html;
    }
    location /llm-testing/ {
        try_files $uri $uri/ /llm-testing/index.html;
    }
    location /status/ {
        try_files $uri $uri/ /status/index.html;
    }
}
